deploy:
  stage: deploy
  image: docker:19.03.12
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.12-dind
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  environment:
    name: production
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - DOCKER_HOST="ssh://$SERVER_USER@$SERVER_HOSTNAME:$SSH_PORT" docker stack deploy -c docker-compose.yml -c docker-compose.prod.yml $SWARM_NAME
